#!/bin/bash

cat <<EOF
+++
+++   NOTE: this script is only needed once (FIRST=T).
+++         (Unless there are really big changes to the code.)
+++         Subsequently just type: make V=0
+++         That should be a LOT faster!
+++
EOF

FIRST=
COMPILER='GNU'

#First the bootstrapper:
if [[ $FIRST == T ]]; then
  git submodule init && git submodule update
  ./bootstrap
fi


if [[ $? != 0 ]]; then
  exit $?
fi

if [[ $COMPILER == *GNU* ]]; then
  cd hdf5
  make CC="gcc" FC="gfortran"
  cd ..
  cd tecplot
  make CC="gcc" FC="gfortran"
  cd ..
  if [[ $COMPILER == *DEBUG* ]]; then
    #FOR DEBUGGING
    ./configure CFLAGS="-Wall -Wuninitialized -O0 -g" FCFLAGS="-cpp -fdefault-real-8 -fdefault-double-8 -fbackslash -g -O0 -ggdb3 -fbounds-check -finit-real=nan -fbacktrace -DGNU" --with-hdf5=hdf5/hdf5-1.8.14/hdf5 --with-tecio=tecplot/tecio-12.0 --enable-debug --disable-shared
  else
    #FOR OPTIMIZATION
    ./configure CFLAGS="-Wall -Wuninitialized -O2" FCFLAGS="-cpp -fdefault-real-8 -fdefault-double-8 -fbackslash -O2" --with-hdf5=hdf5/hdf5-1.8.14/hdf5 --with-tecio=tecplot/tecio-12.0 --disable-shared
  fi
elif [[ $COMPILER == *INTEL* ]]; then
  cd hdf5
  make CC=icc FC=ifort
  cd ..
fi

# Compile stuff.  V=0 cleans up the compiler messages.
make V=0 -j4 -C sc
make V=0 -j4 -C p4est
make V=0
